---
name: 'Git SemVer Release'
description: 'Calculate the current pre-release version from Git tags using Semantic Versioning'
branding:
  icon: 'tag'
  color: 'blue'
outputs:
  version:
    description: 'The calculated version'
    value: ${{ steps.git-semver-release.outputs.version }}
runs:
  using: 'composite'
  steps:
    - name: Run git-semver-release
      id: git-semver-release
      shell: bash
      run: |
        chmod +x "${{ github.action_path }}/git-semver-release"
        version=$("${{ github.action_path }}/git-semver-release" version)
        echo "version=$version" >> "$GITHUB_OUTPUT"
