#!/usr/bin/env bash

is_repository() {
  if git rev-parse --git-dir > /dev/null 2>&1; then
    return 0
  else
    return 1
  fi
}

has_commits() {
  if git log > /dev/null 2>&1; then
    return 0
  else
    return 1
  fi
}

get_describe_output() {
  git describe --always --match 'v*' 2> /dev/null || {
   printf ''
  }
}

get_commit_count() {
  git rev-list HEAD --count
}

get_git_branch() {
  git rev-parse --abbrev-ref HEAD
}

is_dirty() {
  if [ -n "$(git status --porcelain 2>/dev/null)" ]; then
    return 0
  else
    return 1
  fi
}

get_latest_release_tag() {
  git describe --abbrev=0 --match 'v[0-9]*.[0-9]*.[0-9]*' 2>/dev/null || printf ''
}

get_bump_type_for_commits_since_tag() {
  local -r tag="$1"
  local bump_type='patch'

  local range='HEAD'
  if [[ -n $tag ]]; then
    range="$tag..HEAD"
  fi

  local commit_hashes
  commit_hashes="$(git rev-list "$range")"

  local message
  for hash in $commit_hashes; do
    message="$(git log -1 --format=%B "$hash")"

    if [[ $message =~ ^[a-zA-Z]+(\(.+\))?!:\ .+$ || $message =~ BREAKING\ CHANGE:\ .+ ]]; then
      bump_type='major'
      break
    elif [[ $message =~ ^feat(\(.+\))?:\ .+$ ]]; then
      bump_type='minor'
    fi
  done

  printf '%s' "$bump_type"
}

get_latest_tag_for_commit_pointed_by_tag() {
  local -r tag="$1"

  local commit_sha
  commit_sha="$(git rev-list -1 "$tag")"
  git tag --points-at "$commit_sha" --list --sort=-version:refname | head -1
}

version() {
  local -r pre_release_format="$1"
  local -r build_format="$2"
  local -r dirty_indicator="$3"
  local -r output_format="$4"
  local -r version_type="$5"

  local git_describe_output
  git_describe_output="$(get_describe_output)"

  local major_version
  local minor_version
  local patch_version
  local commit_count
  local commit_short_sha

  # Release exists with possible additional commits
  if [[ "$git_describe_output" =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)(-([0-9]+))?(-g([a-f0-9]{7}))?$ ]]; then
    major_version="${BASH_REMATCH[1]}"
    minor_version="${BASH_REMATCH[2]}"
    patch_version="${BASH_REMATCH[3]}"
    commit_count="${BASH_REMATCH[5]}"
    commit_short_sha="${BASH_REMATCH[7]}"

    # If two releases point to the same commit take the latest one
    if [[ "$(get_latest_tag_for_commit_pointed_by_tag "v$major_version.$minor_version.$patch_version")" =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
      major_version="${BASH_REMATCH[1]}"
      minor_version="${BASH_REMATCH[2]}"
      patch_version="${BASH_REMATCH[3]}"
    fi

    if [[ $version_type == 'major' ]]; then
      ((major_version++))
      minor_version='0'
      patch_version='0'
    elif [[ $version_type == 'minor' ]]; then
      ((minor_version++))
      patch_version='0'    
    elif [[ $commit_count -gt 0 ]]; then
      ((patch_version++))
    fi
  # Release does not exist but there are commits
  elif [[ $git_describe_output =~ ^([a-f0-9]{7})$ ]]; then
    major_version='0'
    minor_version='0'
    patch_version='0'

    if [[ $version_type == 'major' ]]; then
      ((major_version++))
    elif [[ $version_type == 'minor' ]]; then
      ((minor_version++))
    elif [[ $version_type == 'patch' ]]; then
      ((patch_version++))
    fi

    commit_count="$(get_commit_count)"
    commit_short_sha="${BASH_REMATCH[1]}"
  # There are no commits
  else
    major_version='0'
    minor_version='0'
    patch_version='0'
  fi

  local version="$major_version.$minor_version.$patch_version"

  if [[ -n $commit_count ]]; then
    pre_release="$pre_release_format"
    pre_release="${pre_release//\$branch/"$(get_git_branch)"}"
    pre_release="${pre_release//\$commit_count/"$commit_count"}"
    pre_release="${pre_release//\$commit_short_sha/"$commit_short_sha"}"

    if is_dirty; then
      pre_release="${pre_release//\$dirty_indicator/"$dirty_indicator"}"
    else
      pre_release="${pre_release//\$dirty_indicator/''}"
    fi
  else
    pre_release="$pre_release_format"
    pre_release="${pre_release//\$branch/"$(get_git_branch)"}"
    pre_release="${pre_release//\$commit_count/''}"
    pre_release="${pre_release//\$commit_short_sha/''}"

    if is_dirty; then
      pre_release="${pre_release//\$dirty_indicator/"$dirty_indicator"}"
    else
      pre_release=''
    fi
  fi

  pre_release="${pre_release//\$separator/'.'}"
  pre_release="$(printf '%s' "$pre_release" | tr -s '.')"
  pre_release="${pre_release%.}"
  pre_release="${pre_release#.}"

  version="$version-$pre_release"
  version="${version%-}"

  printf '%s' "$version"
}

release() {
  local -r pre_release_format="$1"
  local -r build_format="$2"
  local -r dirty_indicator="$3"
  local -r message="$4"
  local -r version_type="$5"

  local version
  version="$(version "$pre_release_format" "$build_format" "$dirty_indicator" 'semver' "$version_type")"

  if [[ $version =~ ^([0-9]+\.[0-9]+\.[0-9]+).*$ ]]; then
      version="${BASH_REMATCH[1]}"
  fi

  local -r tag="v$version"

  if [[ -n $message ]]; then
    git tag --annotate "$tag" --message "${message//\$version/"$version"}"
  else
    git tag --annotate "$tag" --message "Release $version"
  fi
}

conventional() {
  local -r pre_release_format="$1"
  local -r build_format="$2"
  local -r dirty_indicator="$3"
  local -r message="$4"

  local latest_tag
  latest_tag="$(get_latest_release_tag)"

  local version_type
  version_type="$(get_bump_type_for_commits_since_tag "$latest_tag")" || return 1

  release "$pre_release_format" "$build_format" "$dirty_indicator" "$message" "$version_type" || return 2
}

main() {
  if ! is_repository; then
    printf 'fatal: not a Git repository' 1>&2
    return 1
  fi

  if ! has_commits; then
    printf 'error: no commits yet' 1>&2
    return 2
  fi

  declare -A config
  if [[ -f .git-semver-release.properties ]]; then
      while IFS='=' read -r key value; do
         config["$key"]="$value"
      done < .git-semver-release.properties
  fi

  local -r dirty_indicator="${config["dirty_indicator"]:-dirty}"
  local -r pre_release_format="${config["pre_release_format"]:-dev\$separator\$commit_count\$separator\$commit_short_sha\$separator\$dirty_indicator}"
  local -r build_format="${config["build_format"]}"

  local -r mode="$1"

  case "$mode" in
    create-config-file)
      printf 'dirty_indicator=dirty\npre_release_format=dev$separator$commit_count$separator$commit_short_sha$separator$dirty_indicator\nbuild_format=\n' > \
        .git-semver-release.properties || return 3
      ;;
    version)
       local -r output_format="$3"

       version "$pre_release_format" "$build_format" "$dirty_indicator" "$output_format" || return 4
       ;;
    major | minor | patch)
      if is_dirty; then
        printf 'error: uncommitted changes found' 1>&2
        return 5
      fi

      local -r message="$2"
      release "$pre_release_format" "$build_format" "$dirty_indicator" "$message" "$mode" || return 6
      ;;
    *)
      if is_dirty; then
        printf 'error: uncommitted changes found' 1>&2
        return 5
      fi

      local -r message="$1"
      conventional "$pre_release_format" "$build_format" "$dirty_indicator" "$message" || return 7
      ;;
  esac
}

main "$@"
